version: '3.5'

services:

  backend:
    image: backend
    build: .
    environment:
      - REDIS=redis
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - DB_HOST=postgres
    depends_on: 
      - postgres
  frontend:
    image: frontend
    build: .
  redis:
    image: redis:latest
    restart: unless-stopped
  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - database:/var/lib/postgresql/data
  proxy:
    image: jwilder/nginx-proxy
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend

volumes:
  database:
    driver_opts:
      type: none
      device: $PWD/database
      o: bind
