version: '3'

services:

  backend:
    image: backend
    build: .
    ports:
      - 8000:8000
    environment:
      - REDIS=redis
  frontend:
    image: frontend
    build: .
    ports:
      - 5000:5000
  redis:
    image: redis:latest
    restart: unless-stopped
