version: '3.5'

services:

  backend:
    image: backend
    build: .
    ports:
      - 8000:8000
    environment:
      - REDIS=redis
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - DB_HOST=postgres
    depends_on: 
      - postgres
  frontend:
    image: frontend
    build: .
    ports:
      - 5000:5000
    depends_on:
      - backend
  redis:
    image: redis:latest
    restart: unless-stopped
  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: password
